---

- name: RUBY DEBIAN | Installation
  apt:
    name:
      - ruby-full
      - ruby-dev
      - build-essential
      - autogen
      - autoconf
      - libtool
      - rubygems
    state: present
